version: 2.1

jobs:
  lint:
    <<: &image-ruby
      docker:
        - image: cimg/ruby:3.3.6
    steps:
      - checkout
      - run: gem install standard
  lint2:
    <<: *image-ruby
    steps:
      - checkout
      - run: gem install standard
  lint3:
    docker:
      - image: cimg/ruby:3.4.3
    steps:
      - checkout
      - run: gem install standard

workflows:
  pipeline:
    jobs:
      - lint
      - lint2
      - lint3
